name: Analysis
on: [push]

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Important pour que Sonar voit l'historique de code

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      # On génère les rapports bruts (JaCoCo + PiTest)
      - name: Build and Test
        run: mvn clean verify org.pitest:pitest-maven:mutationCoverage

      # On envoie tout au serveur "vitrine"
      - name: Analyze with Sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          mvn sonar:sonar \
          -Dsonar.projectKey=sr-back \
          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml \
          -Dsonar.pitest.mode=reuseReport